// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy2SJkhB_BhGmVtC4CqmNrrGrVBqOvSAw',
    appId: '1:457727618581:web:b09eb564da8891786ee81c',
    messagingSenderId: '457727618581',
    projectId: 'symptoscan-d05e3',
    authDomain: 'symptoscan-d05e3.firebaseapp.com',
    storageBucket: 'symptoscan-d05e3.appspot.com',
    measurementId: 'G-JTMQLW3Q8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_SUeIp8XNHpGSmrnA9861iTkDOenifwA',
    appId: '1:457727618581:android:cfd3660873585eb56ee81c',
    messagingSenderId: '457727618581',
    projectId: 'symptoscan-d05e3',
    storageBucket: 'symptoscan-d05e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZXLH-TXk1f2XF4VAF_6X5_cuBPmno1U',
    appId: '1:457727618581:ios:ce48ac9d0c7dcab26ee81c',
    messagingSenderId: '457727618581',
    projectId: 'symptoscan-d05e3',
    storageBucket: 'symptoscan-d05e3.appspot.com',
    iosBundleId: 'com.example.symptoScanFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIZXLH-TXk1f2XF4VAF_6X5_cuBPmno1U',
    appId: '1:457727618581:ios:c41548ac77e0042b6ee81c',
    messagingSenderId: '457727618581',
    projectId: 'symptoscan-d05e3',
    storageBucket: 'symptoscan-d05e3.appspot.com',
    iosBundleId: 'com.example.symptoScanFlutter.RunnerTests',
  );
}
